version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contactmanager
      SPRING_DATASOURCE_USERNAME: qwell
      SPRING_DATASOURCE_PASSWORD: password
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: qwell
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
